Module skeleton
dbjpanda/collaborative_editors pull request #1
Opened 2019-05-30 18:22 UTC by anantjain6

2019-05-30 20:14 UTC, ankitjain28may commented
Integrate tugboat, write config for it.

2019-05-31 00:02 UTC, dbjpanda commented
> Integrate tugboat, write config for it.

Create another repo "Drupal", make a mirror/subversion/subtree of the repo 'collaborative_editors.' inside Drupal/web/modules/. Push your entire configuration, db-dump etc to 'Drupal' repo. and set up tugboat for that repo. Use https://github.com/drupal-composer/drupal-project to set up your Drupal installation. Hope it's clear.

2019-05-31 00:08 UTC, dbjpanda commented
Also rename those submodules from `collaborative_editor_etherpad` to only etherpad. The name seems very long. You may use a small prefix like `ce`. E.g ce_etherpad

2019-05-31 02:45 UTC, ankitjain28may commented
Don't setup tugboat just for the modules repo, it won't work there.

2019-05-31 18:57 UTC, anantjain6 commented
> Also rename those submodules from `collaborative_editor_etherpad` to only etherpad. The name seems very long. You may use a small prefix like `ce`. E.g ce_etherpad

"ce_etherpad" looks better to me since "etherpad" machine name is already reserved in drupal.org
Added commit for the same

2019-05-31 21:14 UTC, ankitjain28may commented
> > Integrate tugboat, write config for it.
> 
> Create another repo "Drupal", make a mirror/subversion/subtree of the repo 'collaborative_editors.' inside Drupal/web/modules/. Push your entire configuration, db-dump etc to 'Drupal' repo. and set up tugboat for that repo. Use https://github.com/drupal-composer/drupal-project to set up your Drupal installation. Hope it's clear.

Do this, so we can review.

2019-06-02 10:18 UTC, ankitjain28may requested changes
Remove the .module file as it is a blank file.

2019-06-02 10:18 UTC, ankitjain28may commented on modules/ce_etherpad/ce_etherpad.routing.yml
> +  path: '/admin/config/collaborative-editor/etherpad'
collaborative-editors

2019-06-02 10:18 UTC, ankitjain28may commented on modules/ce_etherpad/src/Controller/EtherpadController.php
> +<?php
This file isn't required for now.

2019-06-02 10:18 UTC, ankitjain28may commented on src/Form/CollaborativeEditorsSettingsForm.php
> +<?php
This file is also not required as of now.

2019-06-02 10:18 UTC, ankitjain28may commented on collaborative_editors.links.menu.yml
> +collaborative_editors.admin_config:
Don't make a separate block, Put it under "CONTENT AUTHORING" block

2019-06-02 10:18 UTC, ankitjain28may commented on src/Controller/CollaborativeEditorsController.php
> +  public function plugins() {
Show the plugins under this page like the Etherpad plugin else user won't be able to access the configuration page of the plugin.

2019-06-02 10:18 UTC, ankitjain28may commented on modules/ce_etherpad/ce_etherpad.info.yml
> +
Add the setting button directly here.

2019-06-02 10:18 UTC, ankitjain28may commented on collaborative_editors.info.yml
> +
Add the setting button directly here.

2019-06-05 20:06 UTC, anantjain6 commented
Continued in #2

2019-06-05 20:06 UTC, closed without merging

2019-06-05 20:26 UTC, anantjain6 commented
Continued in #3