Etherpad Logic Phase 1
dbjpanda/collaborative_editors pull request #10
Opened 2019-07-01 14:48 UTC by anantjain6

In continuation to the conversation of #6

2019-07-02 04:51 UTC, ankitjain28may requested changes

2019-07-02 04:51 UTC, ankitjain28may commented on .travis.yml
> +  - ../vendor/bin/phpunit --group collaborative_editors
Add new line at the end

2019-07-02 04:51 UTC, ankitjain28may commented on modules/ce_etherpad/ce_etherpad.libraries.yml
> +    - core/drupalSettings
Add new line at the end

2019-07-02 04:51 UTC, ankitjain28may commented on modules/ce_etherpad/js/editor.js
> +})(Drupal);
Add new line at the end

2019-07-02 05:08 UTC, anantjain6 commented on modules/ce_etherpad/src/Plugin/CollaborativeNetwork/EtherpadEditor.php
> +      $client = new Client($this->apiUrl, $this->apiKey);
This change was a mistake

2019-07-02 05:18 UTC, anantjain6 commented
Suggestions implemented with commit d531577

2019-07-04 03:58 UTC, anantjain6 commented
@ankitjain28may Plz merge the PR

2019-07-04 07:19 UTC, ankitjain28may approved these changes

2019-07-04 07:19 UTC, merged